version: '3'
# https://github.com/docker-library/redis/issues/111

# Communication between multiple docker-compose projects
networks:
  backend:
    driver: bridge
  keycloak_backend:
    external: true
  spring-boot-docker_quarkus:
    external: true


volumes:
  redis-data:

services:
  db:
    image: redis
    restart: unless-stopped
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
#    ports: ['6379:6379'] # the HTTP endpoint
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend
    volumes:
      - redis-data:/data

  gateway-keycloak:
    image: mgperez/gateway-keycloak-jvm
    restart: unless-stopped
    container_name: gateway-keycloak
#    build:
#      context: .
#      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      #KEYCLOAK_HOST: 192.168.1.7:9091 # IP privada en Mac
      KEYCLOAK_HOST: keycloak:8080 # IP network externa
      GW_HOST: gateway:8888
      CONFIG_LOCATION: file:/config/application.yml
      LOGGING_LOCATION: file:/config/logback-spring.xml
    volumes:
      - ./data/gateway-keycloak/config:/config
    links:
      - db:redis
    #external_links:
    #  - keycloak
    ports:
      - 8762:8762
    networks:
      - backend
      - keycloak_backend
      - spring-boot-docker_quarkus
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8762/actuator/health || exit 1"]
      interval: 10s
      timeout: 1s
      retries: 66
