spring:
  profiles:
    active: server
server:
  error:
    include-stacktrace: never
  port: ${PORT:8862}
remote:
  home: http://localhost:9090  # idp
---
spring:
  profiles:
    active: redis
  redis:
    host: redis
    port: 6379
---
spring:
  profiles:
    active: spring-boot
  application:
    name: gateway-keycloak-service
  output.ansi.enabled: ALWAYS
---
spring:
  profiles:
    active: spring-cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/ms_secure/**
          filters:
            - RewritePath=/ms_secure/(?<segment>.*), /$\{segment}
        - id: gateway-service_route
          uri: http://localhost:8888
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*), /$\{segment}
        - id: ibcs-manager_route
          uri: http://localhost:5000
          predicates:
            - Path=/ibcs-manager/**
          filters:
            - RewritePath=/ibcs-manager/(?<segment>.*), /$\{segment}
        - id: api-service_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# actuator-related configuration
# https://www.paradigmadigital.com/dev/monitorizar-microservicios-spring-boot-admin/
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
# https://www.callicoder.com/spring-boot-actuator/
management:
  endpoints:
    web:
      exposure:
        # Expose all monitoring endpoints
        include: "*"
  endpoint:
    health:
      # Always show health test details
      show-details: always
      mail:
        enabled: false # When using the MailService, configure an SMTP server and set this to true

---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${remote.home}/auth/realms/spring-boot-quickstart

## Configuring info endpoint
# https://www.baeldung.com/spring-boot-info-actuator-custom
# https://www.callicoder.com/spring-boot-actuator/
info:
  project:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java-vendor: ${java.specification.vendor}
    java:
      version: @java.version@

---
spring:
  profiles: dev
  redis:
    host: localhost
---
spring:
  profiles:
    active: logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    org.springframework.jdbc: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
#logging.level.io.github.resilience4j: DEBUG
#logging.level.org.springframework.cloud.gateway.filter.factory: TRACE
---
# https://gitlab.com/datastork-examples/spring-keycloak-example/blob/master/src/main/resources/application.yml

